"""Writes NinjaTrader/Presets/SMCPresets.cs: one Strategy per preset, each a subclass of
SMCOrderBlockStrategy whose SetDefaults applies a fixed set of inputs (trading on). The Strategy
Analyzer then needs only strategy + instrument + dates, no per-field typing.

    python backtest/nt8/make_presets.py <presets.json> [--deploy]

presets.json: {"<ClassName>": {"Input": "Value", ...}, ...}. Values are strings as the replica takes
them (enum member names, True/False, numbers). Every preset also writes its closed trades to
Documents\\NinjaTrader 8\\SMC_Results_<ClassName>.csv (the strategy's own result file), which is what
the replica-vs-NT8 comparison reads. --deploy copies the file to bin\\Custom\\Strategies\\Toreda\\.
"""
import json, os, sys, shutil

ENUMS = {"BOSMode": "SmcBosMode", "TimeframePair": "SmcTfPair", "OverlapMode": "SmcOverlapMode", "FVGMode": "SmcFvgMode",
         "MitigationMode": "SmcMitigationMode", "InvalidationMode": "SmcInvalidationMode", "CISDSweepMode": "CisdSweepMode",
         "CISDLevelMode": "CisdLevelMode", "ConnCISDMode": "ConnCisdMode", "ConnRetestMode": "ConnRetestMode", "DebugLogLevel": "SmcLogLevel"}
BOOLS = {"RejectLegViolation", "EnableBull", "EnableBear", "RetestEnabled", "EnableCISD", "CISDSweep", "CISDConfirm", "CISDRetrace",
         "ConnEnable", "ConnMitigationStops", "TrendFilter", "EnableTrading", "RiskPercentMode", "OppositeBlockExit", "RideTrend",
         "EntryAlert", "ConfidenceLog", "BreakEven", "CapitalGuards", "ShowZones", "ShowInactive", "AlertsEnabled"}
DOUBLES = {"SwingMinATR", "BOSBufferATR", "DispATRMult", "DispCandleATRMult", "DispMinBodyPct", "DispMinRelStrength", "OverlapPct",
           "FVGMinATR", "CISDSwingMinATR", "TrendATRMult", "RiskPercent", "TargetRR", "EquityBase", "GuardDailyLoss",
           "GuardWeeklyLoss", "GuardEquityStop", "GuardSpreadPctOfR", "GuardVolSpike"}
STRINGS = {"ConfidenceFile", "ResultFile"}


def literal(name, value):
    v = str(value)
    if name in ENUMS: return f"{ENUMS[name]}.{v}"
    if name in BOOLS: return "true" if v.lower() == "true" else "false"
    if name in STRINGS: return json.dumps(v)
    if name in DOUBLES: return v if "." in v or "e" in v.lower() else v + ".0"
    return v


def main():
    presets = json.load(open(sys.argv[1]))
    out = os.path.join(os.path.dirname(__file__), "..", "..", "NinjaTrader", "Presets", "SMCPresets.cs")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    lines = ["// Generated by backtest/nt8/make_presets.py - SMCOrderBlockStrategy with fixed inputs, for Strategy Analyzer runs.",
             "// Each preset trades (Execute trades on) and logs its closed trades to SMC_Results_<name>.csv.",
             "using NinjaTrader.NinjaScript.Strategies.Toreda.SMCZob;", "",
             "namespace NinjaTrader.NinjaScript.Strategies.Toreda.SMCPresets", "{"]
    for cls, inputs in presets.items():
        inputs = dict(inputs)
        inputs.setdefault("EnableTrading", "True")
        inputs.setdefault("ResultFile", f"SMC_Results_{cls}.csv")
        inputs.setdefault("ConfidenceLog", "False")
        inputs.setdefault("ShowZones", "False")
        lines += [f"    public class {cls} : SMCOrderBlockStrategy", "    {",
                  "        protected override void OnStateChange()", "        {", "            base.OnStateChange();",
                  "            if (State == State.SetDefaults)", "            {", f"                Name = \"{cls}\";"]
        for k, v in inputs.items():
            lines.append(f"                {k} = {literal(k, v)};")
        lines += ["            }", "        }", "    }", ""]
    lines.append("}")
    open(out, "w", newline="\r\n").write("\n".join(lines) + "\n")
    print("wrote", os.path.abspath(out), "with", len(presets), "presets")
    if "--deploy" in sys.argv:
        dest = os.path.join(os.path.expanduser("~"), "OneDrive", "Documents", "NinjaTrader 8", "bin", "Custom", "Strategies", "Toreda", "SMCPresets.cs")
        shutil.copy(out, dest)
        print("deployed to", dest)


if __name__ == "__main__":
    main()
