// Generated by backtest/nt8/make_presets.py - SMCOrderBlockStrategy with fixed inputs, for Strategy Analyzer runs.
// Each preset trades (Execute trades on) and logs its closed trades to SMC_Results_<name>.csv.
using NinjaTrader.NinjaScript.Strategies.Toreda.SMCZob;

namespace NinjaTrader.NinjaScript.Strategies.Toreda.SMCPresets
{
    public class SMCValH1M5 : SMCOrderBlockStrategy
    {
        protected override void OnStateChange()
        {
            base.OnStateChange();
            if (State == State.SetDefaults)
            {
                Name = "SMCValH1M5";
                EnableTrading = true;
                ResultFile = "SMC_Results_SMCValH1M5.csv";
                ConfidenceLog = false;
                ShowZones = false;
            }
        }
    }

    public class SMCValMix : SMCOrderBlockStrategy
    {
        protected override void OnStateChange()
        {
            base.OnStateChange();
            if (State == State.SetDefaults)
            {
                Name = "SMCValMix";
                TimeframePair = SmcTfPair.M15_M1;
                TrendFilter = false;
                ConnCISDMode = ConnCisdMode.Multi;
                ConnRetestMode = ConnRetestMode.Multi;
                TargetRR = 2.0;
                BreakEven = true;
                BreakEvenTicks = 80;
                OppositeBlockExit = true;
                EnableTrading = true;
                ResultFile = "SMC_Results_SMCValMix.csv";
                ConfidenceLog = false;
                ShowZones = false;
            }
        }
    }

    public class SMCValH4Ride : SMCOrderBlockStrategy
    {
        protected override void OnStateChange()
        {
            base.OnStateChange();
            if (State == State.SetDefaults)
            {
                Name = "SMCValH4Ride";
                TimeframePair = SmcTfPair.H4_M15;
                TrendFilter = false;
                RideTrend = true;
                FVGMode = SmcFvgMode.Off;
                EnableTrading = true;
                ResultFile = "SMC_Results_SMCValH4Ride.csv";
                ConfidenceLog = false;
                ShowZones = false;
            }
        }
    }

    public class SMC_MNQ_Rec : SMCOrderBlockStrategy
    {
        protected override void OnStateChange()
        {
            base.OnStateChange();
            if (State == State.SetDefaults)
            {
                Name = "SMC_MNQ_Rec";
                ConnCISDMode = ConnCisdMode.Multi;
                ConnRetestMode = ConnRetestMode.Multi;
                DispATRMult = 1.5;
                DispMinRelStrength = 2.0;
                EnableBear = false;
                MaxAgeBars = 100;
                TargetRR = 0.75;
                TimeframePair = SmcTfPair.H4_M15;
                TrendFilter = false;
                EnableTrading = true;
                ResultFile = "SMC_Results_SMC_MNQ_Rec.csv";
                ConfidenceLog = false;
                ShowZones = false;
            }
        }
    }

    public class SMC_MES_Rec : SMCOrderBlockStrategy
    {
        protected override void OnStateChange()
        {
            base.OnStateChange();
            if (State == State.SetDefaults)
            {
                Name = "SMC_MES_Rec";
                CISDSweep = true;
                DispATRMult = 3.0;
                EnableBear = false;
                MaxAgeBars = 300;
                SwingLength = 6;
                TargetRR = 0.75;
                TrendFilter = false;
                EnableTrading = true;
                ResultFile = "SMC_Results_SMC_MES_Rec.csv";
                ConfidenceLog = false;
                ShowZones = false;
            }
        }
    }

    public class SMC_MYM_Rec : SMCOrderBlockStrategy
    {
        protected override void OnStateChange()
        {
            base.OnStateChange();
            if (State == State.SetDefaults)
            {
                Name = "SMC_MYM_Rec";
                CISDMaxSeries = 6;
                CISDSweep = true;
                ConnCISDMode = ConnCisdMode.Multi;
                ConnRetestMode = ConnRetestMode.Multi;
                EnableBear = false;
                FVGMode = SmcFvgMode.Required;
                SwingLength = 5;
                TimeframePair = SmcTfPair.M15_M1;
                EnableTrading = true;
                ResultFile = "SMC_Results_SMC_MYM_Rec.csv";
                ConfidenceLog = false;
                ShowZones = false;
            }
        }
    }

    public class SMC_MGC_Rec : SMCOrderBlockStrategy
    {
        protected override void OnStateChange()
        {
            base.OnStateChange();
            if (State == State.SetDefaults)
            {
                Name = "SMC_MGC_Rec";
                CISDLevelMode = CisdLevelMode.SeriesOpen;
                CISDSweep = true;
                MaxAgeBars = 100;
                TargetRR = 0.5;
                TimeframePair = SmcTfPair.H4_M15;
                TrendFilter = false;
                EnableTrading = true;
                ResultFile = "SMC_Results_SMC_MGC_Rec.csv";
                ConfidenceLog = false;
                ShowZones = false;
            }
        }
    }

}
